name: 'mixpanel_integration_tests'
version: '0.6.0'
config-version: 2
profile: 'integration_tests'


vars:
  mixpanel: 
    event_table: "{{ ref('event') }}"


seeds:
  mixpanel_integration_tests:
    +column_types:
      _fivetran_synced: timestamp
    event:
      +column_types:
        time: timestamp
        distinct_id: "{{ 'varchar(100)'  if target.type in ('redshift', 'postgres') else 'string'}}"
        device_id: "{{ 'varchar(100)'  if target.type in ('redshift', 'postgres') else 'string'}}"